# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InertiaDjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='text',
        ),
    ]
